# Site settings
site_name: msalign
site_description: "msalign: signal calibration and alignment"
site_author: Lukasz G. Migas
copyright: <a href='http://github.com/lukasz-migas'>Lukasz G. Migas</a>
site_url: https://msalign.lukasz-migas.com
repo_url: https://github.com/lukasz-migas/msalign
edit_uri: https://github.com/lukasz-migas/msalign/tree/master/site-source
use_directory_urls: false

google_analytics: ["UA-130097236-1", "https://msalign.lukasz-migas.com"]
docs_dir: "site-source"
site_dir: "docs"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: true
  - changelog

# Extra CCS
extra_css:
  - /css/justify.css
  - /css/style.css

# Page layout
nav:
  - Home: index.md
  - Installation: main/installation.md
  - Examples:
      - Mass Spectrum: examples/msalign-mass-spectrum.md
      - Single Gaussian: examples/msalign-single-gaussian.md
      - Multi Gaussian: examples/msalign-multi-gaussian.md
  - Reference: main/reference.md
  - Changelog: main/changelog.md
  - About: main/about.md

theme:
  name: material
  # logo: 'assets/images/logo.svg'
  # favicon: 'assets/images/favicon.ico'
  language: "en"
  include_sidebar: true
  palette:
    primary: "blue grey"
    accent: "deep orange"
  feature:
    tabs: false

extra:
  version: 0.1.10
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/lukasz-migas"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/munieq11"
    - icon: fontawesome/solid/link
      link: "https://lukasz-migas.com"
