# Site settings
site_name: msalign
site_description: "msalign: signal calibration and alignment"
site_author: Lukasz G. Migas
copyright: <a href='http://github.com/lukasz-migas'>Lukasz G. Migas</a>
site_url: https://msalign.lukasz-migas.com
repo_url: https://github.com/lukasz-migas/msalign
edit_uri: https://github.com/lukasz-migas/msalign/tree/master/site-source
use_directory_urls: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: true
  - changelog

# Extra CCS
extra_css:
  - /css/justify.css
  - /css/style.css

# Page layout
nav:
  - Home: index.md
  - Installation: main/installation.md
  - Examples:
      - Mass Spectrum: examples/msalign-mass-spectrum.md
      - Single Gaussian: examples/msalign-single-gaussian.md
      - Multi Gaussian: examples/msalign-multi-gaussian.md
  - Reference: main/reference.md
  - Changelog: main/changelog.md
  - About: main/about.md

theme:
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  version: 0.1.10
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/lukasz-migas"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/munieq11"
    - icon: fontawesome/solid/link
      link: "https://lukasz-migas.com"
