version: 2
jobs:
    build:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run:
            name: Clean CircleCI
            command: |
              rm -rf ~/.pyenv;
              rm -rf ~/virtualenvs;
        - restore_cache:
            keys:
              - pip-cache
              - miniconda-cache
        - run:
            name: Install miniconda
            command: |
              if [ ! -d "~/miniconda3" ]; then
                wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                chmod +x ~/miniconda.sh;
                ~/miniconda.sh -b -p ~/miniconda3;
                echo "export PATH=~/miniconda3/bin:$PATH" >> $BASH_ENV;
              else
                echo "Miniconda3 already set up.";
              fi
        - save_cache:
            key: miniconda-cache
            paths:
              - ~/.cache/miniconda
        - run:
            name: Setup Python environment
            command: |
              conda update --yes --quiet conda;
              conda create -n testenv --yes python=3.6;
              source activate testenv;
              pip install -U pip wheel;
              pip install -U -r msalign_requirements.txt --ignore-installed;
              pip install git+https://github.com/lukasz-migas/msalign.git;
              echo $PATH;
              echo $CIRCLE_BRANCH;
              which python;
              which pip;
        - run:
            name: Run msasign
            command: |
              python msalign/__init__.py
        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip